version: '2'
services:
    todo-app:
        image: todo
        external_links:
            - todo-mysql:mysql
            - todo-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/todo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    todo-mysql:
        extends:
            file: mysql.yml
            service: todo-mysql
    todo-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: todo-elasticsearch
